name: End-to-end tests

on:
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # run 9 copies of the current job in parallel
        containers: [ 1, 2, 3 ,4, 5, 6, 7, 8, 9]


    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'Actions example'
    env:
      # pass the Dashboard record key as an environment variable
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      # pass GitHub token to allow accurately detecting a build vs a re-run build
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}