name: End-to-end tests

on:
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        node-version: [ 12.x, 14.x, 16.x ]
        containers: [ 1, 2, 3 ]


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cypress run
        uses: cypress-io/github-action@v2
      with:
       record: true
       parallel: true
    env:
      # pass the Dashboard record key as an environment variable
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      # pass GitHub token to allow accurately detecting a build vs a re-run build
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}